# Generated by Django 6.0.6 on 2026-06-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='created_at',
        ),
    ]
