# Generated by Django 6.0.2 on 2026-06-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0002_rename_date_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='simpleApp.project')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='simpleApp.project')),
            ],
        ),
    ]
