# Generated by Django 6.0.6 on 2026-07-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0003_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='simpleApp.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'قيد التخطيط'), ('active', 'قيد التنفيذ'), ('paused', 'متوقف'), ('completed', 'منجز')], default='planning', max_length=20),
        ),
    ]
